# Generated by Django 2.2.6 on 2020-05-21 07:29

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('boardnum', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('my_id', models.CharField(default='admin', max_length=100, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('ph', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('star', models.IntegerField(default=0)),
                ('boardnumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proj.Board')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
