# Generated by Django 2.2.6 on 2020-05-21 09:01

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('Proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
