# Generated by Django 3.1.1 on 2020-10-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proj', '0002_auto_20200521_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='user',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
